version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
mcwfences = true
mcwroofs = true
quad-lolmsmv = true
lolmcgt = true
darkenchanting = true
variantbookshelves = true
mcwwindows = true
croptopia = true
betternether = true
easymagic = true
betterend = true
easyanvils = true
variantsandventures = true
lolmfv = true
friendsandfoes = true
lolmbv = true
comforts = true
macawsbridgesbop = true
mcwpaths = true
mcwbridges = true
mcwlights = true
mcwtrpdoors = true
the_bumblezone = true
mcwholidays = true
handcrafted = true
ftbquests = true
wilderwild = true
snowrealmagic = true
frostiful = true
advancednetherite = true
biomesoplenty = true
mcwdoors = true
macawsroofsbop = true
enchanted-vertical-slabs = true
variantcomposters = true
grassoverhaul = true
lolmlv = true
chipped = true
winterly = true
endrem = true
lolmft = true
trashcans = true
snuffles = true
lolmcbv = true
sereneseasons = true
movingelevators = true
visualworkbench = true
minecraft = true
animal_feeding_trough = true
tradingpost = true
scorchful = true
dragonloot = true
mcwfurnitures = true
blahaj = true
creeperoverhaul = true
mcwfencesbop = true
waystones = true
beautify = true
knightquest = true
adventurez = true
bosses_of_mass_destruction = true
lolmgv = true
voidz = true
rocks = true
universal_graves = true
lolmblv = true
mobs_of_mythology = true
toms_storage = true
desolation = true
blockus = true
