[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				zoglin = true
				egg = true
				allay = true
				llama = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				glow_item_frame = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				zombie = true
				ender_pearl = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				vex = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				polar_bear = true
				hopper_minecart = true
				painting = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

			[light_sources.settings.entities.uselessreptile]
				lightning_chaser = true
				lightning_breath = true
				moleclaw = true
				river_pikehorn = true
				shockwave_sphere = true
				wyvern = true
				acid_blast = true

			[light_sources.settings.entities.handcrafted]
				seat = true

			[light_sources.settings.entities.livingthings]
				shark = true
				snail = true
				mantaray = true
				monkey = true
				koala = true
				owl = true
				ostrich = true
				baby_ender_dragon = true
				shroomie = true
				flamingo = true
				nether_knight = true
				raccoon = true
				giraffe = true
				peacock = true
				elephant = true
				seahorse = true
				crab = true
				penguin = true

			[light_sources.settings.entities.revampedpiles]
				plains_seat_entity = true
				desert_seat_entity = true

			[light_sources.settings.entities.weeping_angels]
				weeping_angel = true

			[light_sources.settings.entities.variantsandventures]
				verdant = true
				gelid = true
				murk = true
				thicket = true

			[light_sources.settings.entities.knightquest]
				ratman = true
				gremlin = true
				bad_patch = true
				ghastling = true
				eldknight = true
				ghosty = true
				swampman = true
				samhain = true
				eldbomb = true
				lizzy = true

			[light_sources.settings.entities.mobs_of_mythology]
				kobold_warrior = true
				kobold = true
				automaton = true
				drake = true
				sporeling = true
				chupacabra = true

			[light_sources.settings.entities.biomeswevegone]
				pumpkin_warden = true
				oddion = true
				man_o_war = true

			[light_sources.settings.entities.cyclopsmod]
				cyclops_brute = true
				cyclops_ordnance = true
				glacial_cyclops = true
				poison_dart = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				hydrogen_jellyfish = true
				firefly = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.adventurez]
				deer = true
				orc = true
				desert_rhino = true
				the_eye = true
				piglin_beast = true
				ender_whale = true
				blaze_guardian = true
				void_fragment = true
				dragon = true
				brown_fungus = true
				blaze_guardian_shield = true
				nightmare = true
				mini_blackstone_golem = true
				mammoth = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				enderwarthog = true
				void_shadow = true
				red_fungus = true
				amethyst_shard = true
				summoner = true
				void_bullet = true

			[light_sources.settings.entities.frostiful]
				glacial_arrow = true
				frost_spell = true

			[light_sources.settings.entities.duckling]
				duck_egg = true
				duck = true
				quackling = true

			[light_sources.settings.entities.snowpig]
				snow_pig = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.desolation]
				blackened = true
				ash_scuttler = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.dtnpaletteofpaws]
				wolf = true

			[light_sources.settings.entities.snuffles]
				snuffle = true

			[light_sources.settings.entities.lostrelics]
				tainted_blood_crystal = true

			[light_sources.settings.entities.gipples_galore]
				gipple = true
				aneuploidian = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				birch_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				desert_creeper = true
				dark_oak_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				angler_fish = true
				sculk_snapper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				gauntlet = true
				soul_star = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				thrown_stinger_spear = true
				rootmin = true
				bee_queen = true
				variant_bee = true
				honey_crystal_shard = true
				dirt_pellet = true
				beehemoth = true
				sentry_watcher = true

			[light_sources.settings.entities.dragonloot]
				dragon_trident = true

			[light_sources.settings.entities.smallships]
				galley = true
				cog = true
				brigg = true
				cannon_ball = true

			[light_sources.settings.entities.earthtojavamobs]
				pink_footed_pig = true
				cream_cow = true
				flecked_sheep = true
				midnight_chicken = true
				umbra_cow = true
				rainbow_sheep = true
				mottled_pig = true
				bold_striped_rabbit = true
				long_nosed_sheep = true
				amber_chicken = true
				bouldering_zombie = true
				furnace_golem = true
				vested_rabbit = true
				rotten_flesh_projectile = true
				bronzed_chicken = true
				jumbo_rabbit = true
				bone_shard = true
				moobloom = true
				stormy_chicken = true
				rocky_sheep = true
				jolly_llama = true
				fancy_chicken = true
				moolip = true
				sunset_cow = true
				melon_seed_projectile = true
				pale_pig = true
				piebald_pig = true
				muddy_foot_rabbit = true
				dairy_cow = true
				spotted_pig = true
				skeleton_wolf = true
				gold_crested_chicken = true
				muddy_pig = true
				wooly_cow = true
				freckled_rabbit = true
				ashen_cow = true
				sooty_pig = true
				patched_sheep = true
				melon_golem = true
				horned_sheep = true
				harelequin_rabbit = true
				cookie_cow = true
				pinto_cow = true
				fuzzy_sheep = true
				bone_spider = true
				cluckshroom = true
				albino_cow = true
				viler_witch = true
				tropical_slime = true
				inky_sheep = true
				skewbald_chicken = true
				lobber_zombie = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.weaponmod]
				dummy = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				silk_moth = true
				end_slime = true
				end_fish = true

			[light_sources.settings.entities.stellaris]
				martian_raptor = true
				alien_zombie = true
				mogler = true
				pygro = true
				star_crawler = true
				normal_rocket = true
				lander = true
				pygro_brute = true

			[light_sources.settings.entities.eternal_starlight]
				tangled_hatred_part = true
				lunar_monstrosity = true
				crystallized_moth = true
				tangled_skull = true
				chain_of_souls = true
				eye_of_seeking = true
				nightfall_spider = true
				lonestar_skeleton = true
				ent = true
				thirst_walker = true
				lunar_spore = true
				shattered_blade = true
				gatekeeper_fireball = true
				gleech = true
				lunar_thorn = true
				tangled = true
				tangled_hatred = true
				shimmer_lacewing = true
				aethersent_meteor = true
				the_gatekeeper = true
				ratlin = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				rascal = true

			[light_sources.settings.entities.wilderwild]
				firefly = true
				jellyfish = true
				ostrich = true
				scorched = true
				crab = true
				tumbleweed = true
				coconut = true

			[light_sources.settings.entities.chococraft]
				chocobo = true
